sudo: required
services:
    - docker

before_install:
    - docker build -t pushpit07/docker-react -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true pushpit07/docker-react npm run test
# deploy:
#     provider: elasticbeanstalk
#     region: "us-west-2"
#     app: "docker-react"
#     env: "Docker-env"
#     bucket_name: "elasticbeanstalk-us-west-2-306723636626"
#     bucket_path: "docker-react"
#     on:
#         branch: main
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: "$AWS_SECRET_KEY"
