sudo: required
services:
    - docker

before_install:
    - docker build -t pushpit07/docker-react -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true pushpit07/docker-react npm run test
